version: "3.5"

services:
  redis:
    image: redis:5.0.5
    container_name: redis-db
    ports:
      - "7001:6379"
    networks:
      - proxynet

  proxy-redis:
    image: proxy-redis:1.0
    container_name: proxy
    command: java -Xmx2g -Xms2g -jar proxy-redis-1.0-SNAPSHOT.jar server redis-app.yml
    ports:
      - "8080:8080"
    networks:
      - proxynet
    depends_on:
      - redis

  benchmark: # work in progress, refer TODOs for it in README
    image: proxy-redis:1.0
    container_name: benchmark
    command: java -Xmx1g -Xms1g -jar proxy-redis-1.0-SNAPSHOT.jar proxy-load-test -n 100000 -c 8
    networks:
      - proxynet

  benchmark_ab:
    image: jordi/ab
    networks:
      - proxynet

  proxy-build:
    image: proxy-redis:1.0
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: proxy-build
    volumes:
      - $PWD/artifact:/code/proxy-redis/target

  proxy-test: # run maven based tests and build a fat jar
    build:
      context: .
      dockerfile: Dockerfile.test
    command: mvn package # use -DskipTests=true here if there is genuie reason to skip tests
    container_name: proxy-test
    networks:
      - proxynet
    volumes:
      # Below is to speed up maven build on a re-run
      - ~/.m2:/root/.m2
      # Below is to copy fat jar to local filesystem
      # TODO: change fat jar location (likely a setting in pom.xml) so that it can be sync'ed to artifact directory ignoring other files in target/
      - $PWD/artifact:/code/proxy-redis/target
    depends_on:
      - redis

networks:
  proxynet:
